### ISSUE TITLE
annotation shifts away from intended location (with Openseadragon)

### ISSUE THREAD

**Issue by meihuisu** [annotorious/annotorious-v1#148]
I am using Annotorious with Openseadragon on our zoomiable 
microscopy data in DZI. I have noticed some odd behaviour and 
it is happening on the demo page too,
http://annotorious.github.io/demos/openseadragon-preview.html
(I am using firefox 42.0 on a mac laptop)

  Sometimes, after filling in the annotation text and click 
the 'save', the whole annotation overlay shifts away from 
intended location or changes in size.

**Comment by dephora** [comment]
I'm having this issue as well - sometimes it's as little as a couple of px resize without a shift, others it completely resizes and shifts.

**Comment by meihuisu** [comment]
I have updated my openseadragon  and I don't see this problem much except when
my computer did not catch the click-and-drag . I had to compile annotorious from source though.

//! openseadragon 2.1.0
//! Built on 2016-01-26
//! Git commit: v2.0.0-255-a1b7a54
//! http://openseadragon.github.io
//! License: http://openseadragon.github.io/license/

**Comment by harshalitalele** [comment]
I am still getting this issue.
As per my observation, this issue is coming when we have scrollbar.
When we have scrollbar positioned at the top, the annotations are drawn properly.
But if you scroll a bit down, annotations are displaced with same distance after clicking on Save.

Maybe because after clicking on Save, annotations should be placed from document's top location, but it is getting positioned as per window's top location.

But I don't understand where to make changes in code if this is right. (Maybe inside editor.js, but I am not sure)

**Comment by atosti** [comment]
I'm not sure if this will resolve the issue you all are having, but after puzzling over a similar thing for a few days (all my annotations shifted down by a fixed amount on save) I found that putting my OSD viewer inside a relatively positioned div prevented my annotations from moving on save.

The below snippet illustrates my resolution, hopefully it fixes yours as well.
```
<!-- Add relative positioning to the OSD viewer div -->
<div id="openseadragon-viewer" style="position: relative;" class="viewer"></div>
```

**Comment by Paras-Gupta790** [comment]
I am still getting this issue.
When I rotate (say 90 degrees) and then create a new annotation, after pressing save in the popup, the annotation jumps to a different spot from where I had actually marked the area.
