### ISSUE TITLE
Loading annotations for multiple images on same page, from remote server.

### ISSUE THREAD

**Issue by amrutraj** [annotorious/annotorious-v1#48]
Hi,
Thank you very much for your hard work. I am using annotorious, to train Tesseract OCR on my regional languages. I am from India.

I have a problem though. I can annotate multiple images from the same page just fine. But when I try to load previous annotations from a server, a weird thing happens.

Whichever image is in front of the screen, only that image loads the annotations.

E.g.

< script language="javascript">anno.addPlugin('ElasticSearch', { base_url: '/annot' }); < /script>  

---

| Image1.jpg |

---

---

| Image2.jpg |

---

Annotorious only does either 

http://localhost/annot?oldnotes=http://localhost/imgs/image1.jpg 
OR
http://localhost/annot?oldnotes=http://localhost/imgs/image2.jpg

depending on which image is on the screen.

How can I make it load the info for both the pages? Maybe forcefully/separately for each image?

I am using annotorious standalone v 0.3.

Thank you.
- Amrutraj Gore

**Comment by rsimon** [comment]
Hi Amrutraj,

hm - that sounds like it may be a problem with the ElasticSearch plugin rather than with Annotorious. I will take a look!

<I am using annotorious, to train Tesseract OCR on my regional languages.>

That's a really cool use case, by the way! Very exciting! Is there any public demo page of this?

I'll let you know as soon as I know more and can hopefully provide a fix soon!

Cheers,
Rainer

---

Von: Amrutraj Gore [notifications@github.com]
Gesendet: Samstag, 02. Februar 2013 16:33
An: annotorious/annotorious
Betreff: [annotorious] Loading annotations for multiple images on same page, from remote server. (#48)

Hi,
Thank you very much for your hard work. I am using annotorious, to train Tesseract OCR on my regional languages. I am from India.

I have a problem though. I can annotate multiple images from the same page just fine. But when I try to load previous annotations from a server, a weird thing happens.

Whichever image is in front of the screen, only that image loads the annotations.

E.g.

< script language="javascript">anno.addPlugin('ElasticSearch', { base_url: '/annot' }); < /script>

---

| Image1.jpg |

---

---

| Image2.jpg |

---

Annotorious only does either

http://localhost/annot?oldnotes=http://localhost/imgs/image1.jpg
OR
http://localhost/annot?oldnotes=http://localhost/imgs/image2.jpg

depending on which image is on the screen.

How can I make it load the info for both the pages? Maybe forcefully/separately for each image?

I am using annotorious standalone v 0.3.

Thank you.
-   Amrutraj Gore

**Comment by amrutraj** [comment]
Hi,
Currently everything's on localhost. But I will take it to EC2 soon. Its
really cool that you are so involved with something that is going to help
so many people. Easier annotation of images opens up a host of
possibilities.

Have a good day
-Amrutraj.

**Comment by rsimon** [comment]
Thanks for your kind comments!

I tried to reproduce the problem, but can't seem to get the same behavior. I put two images on a test page, and used the ElasticSearch plugin to store annotations on both images. When I reload the page, the annotations re-appear correctly on both images. 

Are you using the CSS class 'annotatable' to active Annotorious? Or the anno.makeAnnotatable method?

If its the latter, it might be a timing problem. Are you calling the .makeAnnotatable method after the page has loaded (in an .onload hanldler)?

Another thing that's maybe worth trying: can you (just to test) hot-link to the latest Annotorious version, instead of v0.3? I made a few changes regarding loading/lazy-loading of images and possibly there was a problem in v0.3 that no longer exists.

Cheers,
Rainer

**Comment by rsimon** [comment]
PS: to hotlink, just add

```
<link type="text/css" rel="stylesheet" href="http://annotorious.github.com/latest/annotorious.css" />
<script type="text/javascript" src="http://annotorious.github.com/latest/annotorious.min.js"></script>
```

to your page head.

**Comment by amrutraj** [comment]
Man, I can not thank you enough. Its working.
Like black magic to me. After spending 6 hours on it I had lost track of
all the changes I made to the annotorious.js. Now I just hotlinked to your
file and changed my code ( esp. paths) to adjust to your naming system
(instead of the other way around), and it just worked. Now annotating is so
beautifully efficient.
Once I get a domain name I will post the link.

Thank you very much.

-Amrutraj Gore.

**Comment by rsimon** [comment]
Excellent! I'm closing this ticket, then. FYI: There will be a 0.3.1 release for download soon. (But you can still keep hot-linking to the hosted version, as well of course.)

And, yes, please do post the link once you have it. Really interesting stuff!

Cheers,
Rainer
