### ISSUE TITLE
Touch Support

### ISSUE THREAD

**Issue by foryougautam** [annotorious/annotorious-v1#52]
Hello All,
Is annotorious is compatible to touch device(IPAD)?

**Comment by rsimon** [comment]
Unfortunately, I don’t have touch support implemented yet. I’d love to do it & it's on my list – but lack of time :-( But in case you are willing to play around and do a little hacking yourself:

There is a github user named @grandecomplex who has added touch support to the Annotator plugin version (not the standalone version) in his own fork of Annotorious:

https://github.com/grandecomplex/annotorious/commits/master

So if you can/want to use the Annotator plugin version, this might already work for you! Otherwise, you could maybe use that code as an example and try to patch touch support into Annotorious standalone yourself? (I’m willing to assist on this & would be highly interested in the results. But I’ll likely have very little time to work on it right now.)

Cheers,
Rainer

PS: I'm hoping to include Alex' very cool touch code into the main Annotorious branch really soon. I'll keep you posted!

**Comment by grandecomplex** [comment]
Hey! I was thinking about this last night. So I'm very busy finishing up my client work. May 1st is my first day of freedom, and my first priority is to go through my code I've changed to annotorious and do a pull request.

Two things worth mentioning
1. Touch support
2. Detecting out of bounds and display annotations inside the image

Touch support will be first my first order of business. Hopefully ya'll can wait until the first week of May.

**Comment by rsimon** [comment]
Touch support based on Alex' code was extended to the standalone version in commits a2a9d5dbde0bb9cdb042d03003376e48d9c21068 and 90186773a5468bf43dca7901496e0fce41af00ee :-) Cheers & Thx!
