### ISSUE TITLE
Save annotations and text?

### ISSUE THREAD

**Issue by henrytwang** [annotorious/annotorious-v1#69]
Would it be possible to save the annotation coordinates and text?

**Comment by rsimon** [comment]
Since there can be no one-size-fits-all solution to storing annotations, this is not part of the Annotorious core. (People will want to store in different types of backends, associate user/login info with annotations, use different server technologies, etc.)

To store annotations, you will need to use the [JavaScript API](https://github.com/annotorious/annotorious/wiki/JavaScript-API) or [implement your own storage plugin](https://github.com/annotorious/annotorious/wiki/Developing-Plugins).

There are two example storage plugins available already:
- The [ElasticSearch plugin](https://github.com/annotorious/annotorious-elasticsearch-plugin) is a demo (!) plugin that stores anonymous annotations on an [ElasticSearch 
  server](http://www.elasticsearch.org/).
- The [Parse.com plugin](https://github.com/dommmel/annotorious-parse-plugin) stores annotations in the
  [Parse.com](http://parse.com) cloud storage service. (This is also anonymous, i.e. there's no way to have
  annotations with login and usernames attached.)

**Comment by rsimon** [comment]
PS: If you have ideas/suggestions/plans for other storage technologies - feel free to leave a note here and I'll add them to the ["Plugin Ideas" Wiki page](https://github.com/annotorious/annotorious/wiki/Plugin-Ideas)!

**Comment by henrytwang** [comment]
Thanks Rainier, this was exactly what I was searching for. I will try to get the Parse.com plugin working and let you know if I can get ahold of another solution!

**Comment by rsimon** [comment]
Perfect - thx!
