### ISSUE TITLE
Getting "Uncaught TypeError: Object [object Object] has no method 'A' " for the Annotorious 

### ISSUE THREAD

**Issue by eknight7** [annotorious/annotorious-v1#79]
I added the following javascript to the example code for annotorius : 
$( document ).ready(function(){
console.log("Annotate image");

var myAnnotation = {
/*\* The URL of the image where the annotation should go **/
src : '640px-Hallstatt.jpg',

/*\* The annotation text **/
text : 'My annotation',

/*\* The annotation shape **/
shapes : [{
  /** The shape type **/
  type : 'rect',

  /*\* The shape geometry (relative coordinates) **/
  geometry : { x : 0.1, y: 0.1, width : 0.4, height: 0.3 }
}]
};

console.log(myAnnotation);
console.log("Adding annotation");
console.log(anno["addAnnotation"]);
console.log(anno);
anno.addAnnotation(myAnnotation);
console.log("Added annotation");
});

But I get the error "Uncaught TypeError: Object [object Object] has no method 'A' "

So I am not being able to add annotations programmatically. Could someone suggest something and help? Thanks!

Please note : I didn't modify the example code, I just added this javascript code separately so that I can programmatically add annotations.

**Comment by rsimon** [comment]
Hi!

This looks alright, except for the issue that Annotorious currently doesn't support relative image URLs (really sorry for this - it's on my list and will be fixed soon). Are you using the most up to date hosted version (http://annotorious.github.io/latest/annotorious.min.js) or release 0.6?

Cheers,
Rainer

---

Von: eknight7 [notifications@github.com]
Gesendet: Dienstag, 10. September 2013 08:13
An: annotorious/annotorious
Betreff: [annotorious] Getting "Uncaught TypeError: Object [object Object] has no method 'A' " for the Annotorious  (#79)

I added the following javascript to the example code for annotorius :
$( document ).ready(function(){
console.log("Annotate image");

var myAnnotation = {
/*\* The URL of the image where the annotation should go **/
src : '640px-Hallstatt.jpg',

/*\* The annotation text **/
text : 'My annotation',

/*\* The annotation shape /
shapes : [{
/ The shape type **/
type : 'rect',

/*\* The shape geometry (relative coordinates) **/
geometry : { x : 0.1, y: 0.1, width : 0.4, height: 0.3 }
}]
};

console.log(myAnnotation);
console.log("Adding annotation");
console.log(anno["addAnnotation"]);
console.log(anno);
anno.addAnnotation(myAnnotation);
console.log("Added annotation");
});

But I get the error "Uncaught TypeError: Object [object Object] has no method 'A' "

So I am not being able to add annotations programmatically. Could someone suggest something and help? Thanks!

Please note : I didn't modify the example code, I just added this javascript code separately so that I can programmatically add annotations.

**Comment by eknight7** [comment]
I am using the latest hosted version.

**Comment by rsimon** [comment]
Hi,

can you paste some code how you're using it (or do you have a sample page online somewhere). Alternatively, you could hot-link to a dev version of Annotorious: http://annotorious.github.io/latest/annotorious.dev.js which won't solve your problem but should provide a more meaningful error message for me to trace down.

Thx,
Rainer

**Comment by eknight7** [comment]
I think I found the problem. I was using '$' variable for using jQuery to select an image to annotate dynamically , and then also using this plugin. The problem doesn't exist when I don't use the '$' variable. Thanks.

**Comment by rsimon** [comment]
Ok, cool! I'll see that I compile a sample for using it with an image lazy-loading lib.

Cheers,
R
